<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EDZ-20170729POB" ignored="0" name="Test" tests="5" failures="2" timestamp="17 六月 2019 03:31:52 GMT" time="47.587" errors="0">
  <testcase name="loginWithMicroBlog" time="27.006" classname="AppiumSelenium.com.AppiumSelenium.AppForYjzx">
    <skipped/>
  </testcase> <!-- loginWithMicroBlog -->
  <testcase name="loginWithMicroBlog" time="0.536" classname="AppiumSelenium.com.AppiumSelenium.AppForYjzx">
    <skipped/>
  </testcase> <!-- loginWithMicroBlog -->
  <testcase name="loginWithMicroBlog" time="0.523" classname="AppiumSelenium.com.AppiumSelenium.AppForYjzx">
    <skipped/>
  </testcase> <!-- loginWithMicroBlog -->
  <testcase name="loginWithMicroBlog" time="0.833" classname="AppiumSelenium.com.AppiumSelenium.AppForYjzx">
    <failure type="java.lang.AssertionError" message="expected [.ui.WelcomeActivity] but found [.ui.main.MainActivity]">
      <![CDATA[java.lang.AssertionError: expected [.ui.WelcomeActivity] but found [.ui.main.MainActivity]
	at AppiumSelenium.com.AppiumSelenium.AppForYjzx.loginWithMicroBlog(AppForYjzx.java:44)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginWithMicroBlog -->
  <testcase name="loginWithMicroBlog" time="29.542" classname="AppiumSelenium.com.AppiumSelenium.AppForYjzx">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at listener.ExecutionListener.onTestFailure(ExecutionListener.java:67)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- loginWithMicroBlog -->
</testsuite> <!-- Test -->
